apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mautrix-signal.fullname" . }}
  labels:
    {{- include "mautrix-signal.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- $config := .Files.Get "files/config.yaml" | toString | fromYaml }}
    {{- $merged := merge .Values.configuration $config }}
    {{- toYaml $merged | nindent 4 }}
    

