apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "solidtime.fullname" . }}-app
  labels:
    app.kubernetes.io/name: {{ include "solidtime.name" . }}-app
    {{- include "solidtime.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "solidtime.name" . }}-app
      app.kubernetes.io/instance: {{ .Release.Name }}-app
  template:
    metadata:
      {{- with .Values.app.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "solidtime.name" . }}-app
        app.kubernetes.io/instance: {{ .Release.Name }}-app      
        {{- include "solidtime.labels" . | nindent 8 }}
        {{- with .Values.app.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.app.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.app.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-app
          env:
            - name: CONTAINER_MODE
              value: http
            - name: AUTO_DB_MIGRATE
              value: {{ .Values.config.app.autoDbMigrate | quote }}
          securityContext:
            {{- toYaml .Values.app.securityContext | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "solidtime.fullname" . }}
            - secretRef:
                name: {{ include "solidtime.fullname" . }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.app.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.app.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          volumeMounts:
            - name: app-data
              mountPath: /var/www/html/storage
            - name: app-cache
              mountPath: /var/www/html/bootstrap/cache  
            - name: tmp-dir
              mountPath: /tmp        
            - name: log-dir
              mountPath: /var/log/supervisor
          {{- with .Values.app.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: {{ include "solidtime.fullname" . }}            
        - name: app-cache
          emptyDir: 
            sizeLimit: {{ .Values.app.cache.sizeLimit | quote }}
        - name: tmp-dir
          emptyDir: 
            sizeLimit: {{ .Values.app.tmp.sizeLimit | quote }}
        - name: log-dir
          emptyDir: 
            sizeLimit: {{ .Values.app.logs.sizeLimit | quote }}
      {{- with .Values.app.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
