apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "solidtime.fullname" . }}
  labels:
    {{- include "solidtime.labels" . | nindent 4 }}
data:
  APP_DEBUG: {{ .Values.config.app.debug | quote }}
  APP_DOMAIN: {{ .Values.config.app.domain | quote }}
  APP_ENV: {{ .Values.config.app.env | quote }}
  APP_FORCE_HTTPS: {{ .Values.config.app.forceHttps | quote }}
  APP_KEY: {{ .Values.config.app.key | quote }}
  APP_NAME: {{ .Values.config.app.name | quote }}
  APP_URL: {{ .Values.config.app.url | quote }}
  DB_CONNECTION: {{ .Values.config.db.connection | quote }}
  DB_HOST: {{ .Values.config.db.host | quote }}
  DB_PORT: {{ .Values.config.db.port | quote }}
  DB_SSLMODE: {{ .Values.config.db.sslmode | quote }}
  LOG_CHANNEL: {{ .Values.config.log.channel | quote }}
  LOG_LEVEL: {{ .Values.config.log.level | quote }}
  MAIL_MAILER: {{ .Values.config.mail.mailer | quote }}
  MAIL_ENCRYPTION: {{ .Values.config.mail.encryption | quote }}
  MAIL_FROM_ADDRESS: {{ .Values.config.mail.fromAddress | quote }}
  MAIL_FROM_NAME: {{ .Values.config.mail.fromName | quote }}
  MAIL_HOST: {{ .Values.config.mail.host | quote }}
  MAIL_PORT: {{ .Values.config.mail.port | quote }}
  FILESYSTEM_DISK: {{ .Values.config.filesystem.disk | quote }}
  PUBLIC_FILESYSTEM_DISK: {{ .Values.config.filesystem.publicDisk | quote }}
  QUEUE_CONNECTION: {{ .Values.config.queue.connection | quote }}
  TRUSTED_PROXIES: {{ .Values.config.network.trustedProxies | quote }}
  VITE_APP_NAME: {{ .Values.config.vite.appName | quote }}

