apiVersion: v1
kind: Secret
metadata:
  name: {{ include "solidtime.fullname" . }}
  labels:
    {{- include "solidtime.labels" . | nindent 4 }}  
type: Opaque
data:
  DB_DATABASE: {{ .Values.config.db.database | b64enc | quote }}
  DB_USERNAME: {{ .Values.config.db.username | b64enc | quote }}
  DB_PASSWORD: {{ .Values.config.db.password | b64enc | quote }}
  MAIL_USERNAME: {{ .Values.config.mail.username | b64enc | quote }}
  MAIL_PASSWORD: {{ .Values.config.mail.password | b64enc | quote }}
  APP_KEY: {{ .Values.config.app.key | b64enc | quote }}
  PASSPORT_PRIVATE_KEY: {{ .Values.config.passport.privateKey | b64enc | quote }}
  PASSPORT_PUBLIC_KEY: {{ .Values.config.passport.publicKey | b64enc | quote }}
  SUPER_ADMINS: {{ .Values.config.admins.super | b64enc | quote }}